"""Generate README.md from the curated MCP server registry."""

from __future__ import annotations

from collections import defaultdict

from __version__ import __version__
from data import SERVERS, Category, Server


def _badge(label: str, message: str, color: str) -> str:
    label = label.replace(" ", "%20")
    message = str(message).replace(" ", "%20").replace("-", "--")
    return f"![{label}](https://img.shields.io/badge/{label}-{message}-{color})"


def _row(s: Server) -> str:
    name = f"[{s.name}]({s.repo or s.homepage})" if (s.repo or s.homepage) else s.name
    official = "✅" if s.official else ""
    auth = "🔑" if s.auth_required else ""
    transports = ", ".join(t.value for t in s.transports)
    install = f"`{s.install}`" if s.install else ""
    return f"| {name} | {s.description} | {s.maintainer} {official} | {s.language} | {transports} {auth} | {install} |"


def generate() -> str:
    total = len(SERVERS)
    official = sum(1 for s in SERVERS if s.official)
    categories = sorted({s.category for s in SERVERS}, key=lambda c: c.label)

    by_cat: dict[Category, list[Server]] = defaultdict(list)
    for s in SERVERS:
        by_cat[s.category].append(s)

    out: list[str] = []
    out.append("<!-- AUTO-GENERATED by report.py — run `python main.py generate` to refresh. -->")
    out.append("# 🔌 MCP Servers Directory\n")
    out.append(" ".join([
        _badge("version", __version__, "blue"),
        _badge("servers", total, "green"),
        _badge("official", official, "brightgreen"),
        _badge("categories", len(categories), "purple"),
        "[![CI](https://github.com/Amarel-Taylor-Scott/mcp-servers-directory/actions/workflows/ci.yml/badge.svg)]"
        "(https://github.com/Amarel-Taylor-Scott/mcp-servers-directory/actions/workflows/ci.yml)",
        "[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](LICENSE)",
    ]))
    out.append("")
    out.append("> A curated, machine-readable directory of **Model Context Protocol (MCP)** "
               "servers — the small programs that expose tools, resources, and prompts to "
               "MCP clients like Claude Desktop, IDEs, and agents.\n")
    out.append("MCP is an open standard for connecting LLM apps to external systems. "
               "This repo catalogs public servers with links and install commands, and ships "
               "a small CLI to search/filter/export the registry. Entries link to their "
               "upstream projects — no third-party code is vendored here.\n")

    out.append("## Quick start\n")
    out.append("```bash")
    out.append("pip install -e .            # or: pip install -r requirements.txt")
    out.append("mcp-dir list                # list all servers")
    out.append("mcp-dir search postgres     # search name/description/tags")
    out.append("mcp-dir categories          # show categories + counts")
    out.append("mcp-dir export --format json > servers.json")
    out.append("mcp-dir generate            # regenerate this README")
    out.append("```\n")

    out.append("## At a glance\n")
    out.append(f"- **{total}** servers across **{len(categories)}** categories")
    out.append(f"- **{official}** official / first-party servers (✅)")
    out.append("- 🔑 = requires an API key / auth · transports: `stdio`, `sse`, `http`\n")

    out.append("## Servers by category\n")
    for cat in sorted(by_cat, key=lambda c: c.label):
        servers = sorted(by_cat[cat], key=lambda s: (not s.official, s.name.lower()))
        out.append(f"### {cat.label} ({len(servers)})\n")
        out.append("| Server | Description | Maintainer | Lang | Transport | Install |")
        out.append("|--------|-------------|------------|------|-----------|---------|")
        out.extend(_row(s) for s in servers)
        out.append("")

    out.append("## What is MCP?\n")
    out.append("The Model Context Protocol standardizes how applications provide context to "
               "LLMs. A **client** (e.g. Claude Desktop) connects to one or more **servers**, "
               "each of which exposes *tools* (actions), *resources* (data), and *prompts*. "
               "Learn more at <https://modelcontextprotocol.io>.\n")

    out.append("## Contributing\n")
    out.append("Add or correct an entry in [`data.py`](data.py), run `python main.py generate`, "
               "and open a PR. See [CONTRIBUTING.md](CONTRIBUTING.md) and "
               "[CODE_OF_CONDUCT.md](CODE_OF_CONDUCT.md). Listings are pointers to public "
               "projects; if you maintain a server and want it changed or removed, open an issue.\n")

    out.append("## License\n")
    out.append("[MIT](LICENSE) © Amarel Taylor Scott. Catalog metadata only; each linked "
               "server is governed by its own license.\n")
    return "\n".join(out)


if __name__ == "__main__":
    print(generate())
